### ISSUE TITLE
Unescaped CRC bytes in goTennaDev.execute()

### ISSUE THREAD

**Issue by a-f-G-U-C** [sybip/pyGT#1]
In `goTennaDev` function `execute`, the 0x10 character escaping is currently performed **before** appending the 16-bit CRC. 
This causes the CRC to be sent unescaped over BLE, resulting in protocol corruption if the CRC itself contains a 0x10 character.

https://github.com/sybip/pyGT/blob/8d9fc2939df3ef9ebc41d1b055fedb529c0f3f4b/gtdevice.py#L164-L168

The problem can be fixed by appending the CRC before escaping.

**Comment by sybip** [comment]
Thank you for the report. I need to test this, but looks spot on.

**Comment by sybip** [comment]
Fixed in commit 9d0e4526ce9a3a0df2d1ccedd21461f35e87ac95 (fixed). Thanks again!
